---
deployment:
      tasks:
        - export DEPLOYPATH=/home/hmhofmn2/public_html/junior_dev_codignitor/
        - / -R application $DEPLOYPATH
				- / -R assets $DEPLOYPATH
				- / -R css $DEPLOYPATH
				- / -R img $DEPLOYPATH
				- / -R js $DEPLOYPATH
				- / -R system $DEPLOYPATH
				- / -R trumbowyg $DEPLOYPATH
				- / -R uploads $DEPLOYPATH
				- / .htaccess $DEPLOYPATH
				- / index.php $DEPLOYPATH