---
deployment:
      tasks:
        - export DEPLOYPATH=/home/hmhofmn2/public_html
        - /home/hmhofmn2/repositories/junior_dev_codignitor application $DEPLOYPATH
	- /home/hmhofmn2/repositories/junior_dev_codignitor assets $DEPLOYPATH
	- /home/hmhofmn2/repositories/junior_dev_codignitor css $DEPLOYPATH
	- /home/hmhofmn2/repositories/junior_dev_codignitor img $DEPLOYPATH
	- /home/hmhofmn2/repositories/junior_dev_codignitor js $DEPLOYPATH
	- /home/hmhofmn2/repositories/junior_dev_codignitor system $DEPLOYPATH
	- /home/hmhofmn2/repositories/junior_dev_codignitor trumbowyg $DEPLOYPATH
	- /home/hmhofmn2/repositories/junior_dev_codignitor uploads $DEPLOYPATH
	- /home/hmhofmn2/repositories/junior_dev_codignitor .htaccess $DEPLOYPATH
	- /home/hmhofmn2/repositories/junior_dev_codignitor index.php $DEPLOYPATH
       
        
        