---
deployment:
      tasks:
        - export DEPLOYPATH=/home/hmhofmn2/public_html/junior_dev_codignitor/
        - /bin/cp -R application $DEPLOYPATH
				- /bin/cp -R assets $DEPLOYPATH
				- /bin/cp -R css $DEPLOYPATH
				- /bin/cp -R img $DEPLOYPATH
				- /bin/cp -R js $DEPLOYPATH
				- /bin/cp -R system $DEPLOYPATH
				- /bin/cp -R trumbowyg $DEPLOYPATH
				- /bin/cp -R uploads $DEPLOYPATH
				- /bin/cp .htaccess $DEPLOYPATH
				- /bin/cp index.php $DEPLOYPATH